# Generated by Django 5.1.7 on 2025-03-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('is_realsense', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.IntegerField()),
            ],
        ),
    ]
